# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: keyrock_ob_aggregator.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bkeyrock_ob_aggregator.proto\x12\torderbook\"\x07\n\x05\x45mpty\"Y\n\x07Summary\x12\x0e\n\x06spread\x18\x01 \x01(\x01\x12\x1e\n\x04\x62ids\x18\x02 \x03(\x0b\x32\x10.orderbook.Level\x12\x1e\n\x04\x61sks\x18\x03 \x03(\x0b\x32\x10.orderbook.Level\"8\n\x05Level\x12\x10\n\x08\x65xchange\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x32L\n\x13OrderbookAggregator\x12\x35\n\x0b\x42ookSummary\x12\x10.orderbook.Empty\x1a\x12.orderbook.Summary0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'keyrock_ob_aggregator_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=42
  _EMPTY._serialized_end=49
  _SUMMARY._serialized_start=51
  _SUMMARY._serialized_end=140
  _LEVEL._serialized_start=142
  _LEVEL._serialized_end=198
  _ORDERBOOKAGGREGATOR._serialized_start=200
  _ORDERBOOKAGGREGATOR._serialized_end=276
# @@protoc_insertion_point(module_scope)
