# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import keyrock_ob_aggregator_pb2 as keyrock__ob__aggregator__pb2


class OrderbookAggregatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BookSummary = channel.unary_stream(
                '/orderbook.OrderbookAggregator/BookSummary',
                request_serializer=keyrock__ob__aggregator__pb2.Empty.SerializeToString,
                response_deserializer=keyrock__ob__aggregator__pb2.Summary.FromString,
                )


class OrderbookAggregatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BookSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderbookAggregatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BookSummary': grpc.unary_stream_rpc_method_handler(
                    servicer.BookSummary,
                    request_deserializer=keyrock__ob__aggregator__pb2.Empty.FromString,
                    response_serializer=keyrock__ob__aggregator__pb2.Summary.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orderbook.OrderbookAggregator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


class OrderbookAggregator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BookSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/orderbook.OrderbookAggregator/BookSummary',
            keyrock__ob__aggregator__pb2.Empty.SerializeToString,
            keyrock__ob__aggregator__pb2.Summary.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
